# Generated by Django 3.2.9 on 2021-11-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='Shop_price',
            field=models.IntegerField(default=0, verbose_name='가격'),
        ),
    ]
