# Generated by Django 3.2.9 on 2021-11-30 14:14

from django.db import migrations, models
import shop.upload_to


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_Shop_shop_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='Shop_photo',
            field=models.ImageField(blank=True, upload_to=shop.upload_to.uuid_name_upload_to, verbose_name='사진'),
        ),
    ]
