# Generated by Django 3.2.9 on 2021-11-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shop_title', models.CharField(max_length=200, verbose_name='제목')),
                ('Shop_cartegory', models.CharField(choices=[('생활가전', '생활가전'), ('디지털기기', '디지털기기'), ('여성의류', '여성의류'), ('남성의류', '남성의류')], default='', max_length=10, verbose_name='카테고리')),
                ('Shop_author_name', models.CharField(max_length=20, verbose_name='작성자')),
                ('Shop_price', models.IntegerField(default=0, verbose_name='가격')),
                ('Shop_content', models.TextField(verbose_name='본문')),
                ('Shop_photo', models.ImageField(blank=True, upload_to='', verbose_name='사진')),
                ('Shop_created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('Shop_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
