# Generated by Django 3.2.9 on 2021-11-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='상품 번호')),
                ('category', models.CharField(max_length=20, verbose_name='카테고리')),
                ('name', models.CharField(max_length=20, verbose_name='상품명')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
                ('gift', models.BooleanField(default=0, verbose_name='포장여부')),
                ('gift_date', models.DateTimeField(default=0, verbose_name='원하는 배달 시간')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='주문 날짜')),
            ],
        ),
    ]
