# Generated by Django 3.2.9 on 2021-11-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='client',
            field=models.CharField(default=0, max_length=20, verbose_name='주문자 성함'),
        ),
        migrations.AddField(
            model_name='item',
            name='deliver',
            field=models.TextField(default=0, max_length=120, verbose_name='배송시 요청사항'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='주문 번호'),
        ),
    ]
