# Generated by Django 3.2.10 on 2021-12-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='photo',
            field=models.ImageField(default=1, upload_to='blog/post/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
