# Generated by Django 3.2.9 on 2021-12-06 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='병원 이름')),
                ('address', models.CharField(max_length=100, verbose_name='주소')),
                ('weekdaytime', models.CharField(max_length=30, verbose_name='평일 운영시간')),
                ('sattime', models.CharField(max_length=30, verbose_name='토요일 운영시간')),
                ('hdaytime', models.CharField(max_length=30, verbose_name='일요일/공휴일 운영시간')),
                ('telephone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{2,3,4}-?\\d{3,4}-?\\d{4}$', message='전화번호를입력해주세요.')], verbose_name='대표 전화번호')),
                ('controlcenter', models.CharField(max_length=30, verbose_name='관할보건소')),
                ('centertel', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{2,3,4}-?\\d{3,4}-?\\d{4}$', message='전화번호를입력해주세요.')], verbose_name='관할보건소 전화번호')),
                ('afdp', models.TextField(blank=True, verbose_name='장애인 편의사항')),
            ],
        ),
    ]
