# Generated by Django 3.2.9 on 2021-11-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211129_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AddField(
            model_name='item',
            name='order_date',
            field=models.DateTimeField(auto_now=True, verbose_name='배달 시간'),
        ),
    ]
