# Generated by Django 3.2.9 on 2021-11-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20211129_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='order_date',
            field=models.DateTimeField(auto_now=True, verbose_name='배달시간'),
        ),
    ]
