# Generated by Django 3.2.9 on 2021-11-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20211129_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gift',
            field=models.BooleanField(default=0, verbose_name='포장여부'),
        ),
        migrations.AddField(
            model_name='item',
            name='gift_date',
            field=models.DateTimeField(default=0, verbose_name='원하는 배달 시간'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0, verbose_name='가격'),
        ),
    ]
